### ISSUE TITLE
[2013] Westpac tight-lipped over privacy breach | Stuff.co.nz

### ISSUE THREAD

**Issue by hrbrmstr** [vz-risk/VCDB#2924] opened 2014-06-19 21:13 UTC
http://www.stuff.co.nz/manawatu-standard/news/8502907/Westpac-tight-lipped-over-privacy-breach

**Comment by swidup** [comment] 2018-06-07 16:35
Duplicate of #2971

**Closed by swidup** 2018-06-07 16:35 UTC
Labels: duplicate
