### ISSUE TITLE
Data from police sites leaked on darknet, prone to abuse - Bengaluru City Police

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#12203] opened 2018-09-13 21:06 UTC
http://www.newindianexpress.com/cities/bengaluru/2018/sep/11/data-from-police-sites-leaked-on-darknet-prone-to-abuse-1870687.html

**Comment by gdbassett** [comment] 2020-11-10 21:15
Potentially the data from https://timesofindia.indiatimes.com/city/bengaluru/Karnataka-police-website-hacked-by-alleged-Pak-hackers/articleshow/52686514.cms and https://latesthackingnews.com/2014/04/25/website-of-bangalore-city-police-hacked-and-defaced/ being resold.

**Comment by gdbassett** [comment] 2020-11-10 21:16
Potentially duplicate of https://github.com/vz-risk/VCDB/blob/8c8798f2999fd19330a30ca685fc31994351956b/data/json/validated/6c2f09a2-565a-47a7-8c83-1351ba73a468.json.

**Closed by gdbassett** 2020-11-10 21:16 UTC
Labels: Breach, Hacking, duplicate, random_assignment
